name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  preview-docs:
    runs-on: blacksmith-4vcpu-ubuntu-2204

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: useblacksmith/setup-node@v5
        with:
          node-version: "18"

      - name: Install Fern
        run: npm install -g fern-api

      - name: Generate Documentation Preview with Fern
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: fern generate --docs --preview
