name: ci

on:
  pull_request_target:
    branches:
      - main
jobs:
  preview-docs:
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout PR
        if: github.event_name == 'pull_request_target'
        run: |
          git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-${{ github.event.pull_request.number }}
          git checkout pr-${{ github.event.pull_request.number }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Fern
        run: npm install -g fern-api

      - name: Generate Documentation Preview with Fern
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: fern generate --docs --preview
