name: Spellcheck

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run spellcheck
        uses: streetsidesoftware/cspell-action@v6
        with:
          files: |
            **/*.md
            **/*.mdx
            **/*.yml
            **/*.yaml
          config: .cspell.json
          incremental_files_only: false